//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookstore.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderBook
    {
        public int OrderId { get; set; }
        public int BookId { get; set; }
        public int BookQuantityInOrder { get; set; }
        public int OrderBooksId { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Order Order { get; set; }
    }
}
