//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookstore.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Windows;

    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderBooks = new HashSet<OrderBook>();
        }


        public int OrderId { get; set; }
        public int OrderStatus { get; set; }
        public int PickUpPointID { get; set; }
        public int PickUpCode { get; set; }
        public System.DateTime DeliveryTime { get; set; }
    
        public virtual PickUpPoint PickUpPoint { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderBook> OrderBooks { get; set; }
    }
}
